-- SQL import for Supabase/PostgreSQL generated from current project schema
-- Note: Supabase SQL Editor does not allow CREATE DATABASE.
-- If needed on a standalone PostgreSQL server, run:
-- CREATE DATABASE nhatduc_software;

BEGIN;

CREATE SCHEMA IF NOT EXISTS public;
SET search_path TO public;

CREATE TABLE IF NOT EXISTS "Teachers" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName" TEXT NOT NULL,
    "Phone" TEXT,
    "Email" TEXT,
    "Status" TEXT NOT NULL DEFAULT 'Active',
    "DateOfBirth" TEXT,
    "Address" TEXT,
    "Qualification" TEXT,
    "TeachingSubjects" TEXT
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username" TEXT NOT NULL UNIQUE,
    "PasswordHash" TEXT NOT NULL,
    "Role" TEXT NOT NULL,
    "TeacherId" BIGINT NULL,
    CONSTRAINT "FK_Users_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers"("Id")
);

CREATE TABLE IF NOT EXISTS "Students" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName" TEXT NOT NULL,
    "Phone" TEXT,
    "Email" TEXT,
    "BirthYear" INTEGER NULL,
    "Address" TEXT NULL,
    "Language" TEXT NOT NULL,
    "Status" TEXT NOT NULL DEFAULT 'Active',
    "CreatedAt" TEXT NOT NULL,
    "Balance" NUMERIC(18,2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "StudentBalanceHistory" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StudentId" BIGINT NOT NULL,
    "OldBalance" NUMERIC(18,2) NOT NULL,
    "NewBalance" NUMERIC(18,2) NOT NULL,
    "UpdatedAt" TEXT NOT NULL,
    "UpdatedBy" BIGINT NOT NULL,
    CONSTRAINT "FK_StudentBalanceHistory_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "FK_StudentBalanceHistory_Users_UpdatedBy" FOREIGN KEY ("UpdatedBy") REFERENCES "Users"("Id")
);

CREATE TABLE IF NOT EXISTS "Courses" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" TEXT NOT NULL UNIQUE,
    "Name" TEXT NOT NULL,
    "Language" TEXT NOT NULL,
    "TuitionFee" NUMERIC(18,2) NOT NULL,
    "DurationHours" INTEGER NOT NULL,
    "Status" TEXT NOT NULL DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS "Classes" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClassName" TEXT NOT NULL,
    "CourseId" BIGINT NOT NULL,
    "TeacherId" BIGINT NULL,
    "MaxSize" INTEGER NOT NULL,
    "Status" TEXT NOT NULL DEFAULT 'Active',
    "InactiveFromWeekStart" TEXT NULL,
    CONSTRAINT "FK_Classes_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses"("Id"),
    CONSTRAINT "FK_Classes_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers"("Id")
);

CREATE TABLE IF NOT EXISTS "ClassSchedules" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClassId" BIGINT NOT NULL,
    "DayOfWeek" TEXT NOT NULL,
    "StartTime" TEXT NOT NULL,
    "EndTime" TEXT NOT NULL,
    "Room" TEXT,
    CONSTRAINT "FK_ClassSchedules_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id")
);

CREATE TABLE IF NOT EXISTS "ClassWeeklySchedules" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClassId" BIGINT NOT NULL,
    "WeekStartDate" TEXT NOT NULL,
    "DayOfWeek" INTEGER NOT NULL CHECK ("DayOfWeek" BETWEEN 0 AND 6),
    "ShiftNumber" INTEGER NOT NULL CHECK ("ShiftNumber" BETWEEN 1 AND 5),
    CONSTRAINT "FK_ClassWeeklySchedules_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "UQ_ClassWeeklySchedules_UniqueSlot" UNIQUE ("ClassId", "WeekStartDate", "DayOfWeek", "ShiftNumber")
);

CREATE TABLE IF NOT EXISTS "StudentCourses" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StudentId" BIGINT NOT NULL,
    "CourseId" BIGINT NOT NULL,
    "EnrollDate" TEXT NOT NULL,
    "Status" TEXT NOT NULL,
    CONSTRAINT "FK_StudentCourses_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "FK_StudentCourses_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses"("Id")
);

CREATE TABLE IF NOT EXISTS "ClassStudents" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClassId" BIGINT NOT NULL,
    "StudentId" BIGINT NOT NULL,
    "JoinedDate" TEXT NOT NULL,
    CONSTRAINT "FK_ClassStudents_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "FK_ClassStudents_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "UQ_ClassStudents_ClassId_StudentId" UNIQUE ("ClassId", "StudentId")
);

CREATE TABLE IF NOT EXISTS "Payments" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StudentId" BIGINT NOT NULL,
    "ClassId" BIGINT NULL,
    "Amount" NUMERIC(18,2) NOT NULL,
    "PaymentDate" TEXT NOT NULL,
    "Note" TEXT,
    "CreatedBy" BIGINT NOT NULL,
    CONSTRAINT "FK_Payments_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "FK_Payments_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "FK_Payments_Users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "Users"("Id")
);

CREATE TABLE IF NOT EXISTS "RevenueLedger" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourcePaymentId" BIGINT NULL UNIQUE,
    "Amount" NUMERIC(18,2) NOT NULL,
    "PaymentDate" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "AttendanceSessions" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClassId" BIGINT NOT NULL,
    "SessionDate" TEXT NOT NULL,
    "ShiftNumber" INTEGER NOT NULL DEFAULT 1,
    "CreatedByTeacherId" BIGINT NOT NULL,
    CONSTRAINT "FK_AttendanceSessions_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "FK_AttendanceSessions_Teachers_CreatedByTeacherId" FOREIGN KEY ("CreatedByTeacherId") REFERENCES "Teachers"("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_AttendanceSessions_ClassId_SessionDate_ShiftNumber"
ON "AttendanceSessions"("ClassId", "SessionDate", "ShiftNumber");

CREATE TABLE IF NOT EXISTS "AttendanceRecords" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SessionId" BIGINT NOT NULL,
    "StudentId" BIGINT NOT NULL,
    "Status" TEXT NOT NULL,
    CONSTRAINT "FK_AttendanceRecords_AttendanceSessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "AttendanceSessions"("Id"),
    CONSTRAINT "FK_AttendanceRecords_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "UQ_AttendanceRecords_SessionId_StudentId" UNIQUE ("SessionId", "StudentId")
);

CREATE TABLE IF NOT EXISTS "StudentEvaluations" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StudentId" BIGINT NOT NULL,
    "ClassId" BIGINT NOT NULL,
    "TeacherId" BIGINT NOT NULL,
    "Score" NUMERIC(5,2) NULL,
    "Comment" TEXT,
    "CreatedAt" TEXT NOT NULL,
    CONSTRAINT "FK_StudentEvaluations_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "FK_StudentEvaluations_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "FK_StudentEvaluations_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers"("Id")
);

CREATE TABLE IF NOT EXISTS "TeacherClassPayRates" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TeacherId" BIGINT NOT NULL,
    "ClassId" BIGINT NOT NULL,
    "PayPerShift" NUMERIC(18,2) NOT NULL DEFAULT 100000,
    CONSTRAINT "FK_TeacherClassPayRates_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers"("Id"),
    CONSTRAINT "FK_TeacherClassPayRates_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "UQ_TeacherClassPayRates_TeacherId_ClassId" UNIQUE ("TeacherId", "ClassId")
);

CREATE TABLE IF NOT EXISTS "DataProtectionKeys" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FriendlyName" TEXT NULL,
    "Xml" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "TeacherPayAdjustments" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TeacherId" BIGINT NOT NULL,
    "Year" INTEGER NOT NULL,
    "Month" INTEGER NOT NULL,
    "ShiftCount" INTEGER NOT NULL,
    "PayPerShift" NUMERIC(18,2) NOT NULL,
    "Note" TEXT,
    "CreatedByUserId" BIGINT NOT NULL,
    "CreatedByUsername" TEXT NOT NULL,
    "CreatedAt" TEXT NOT NULL,
    CONSTRAINT "FK_TeacherPayAdjustments_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers"("Id"),
    CONSTRAINT "FK_TeacherPayAdjustments_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id")
);

CREATE TABLE IF NOT EXISTS "TeacherTimesheets" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TeacherId" BIGINT NOT NULL,
    "WorkDate" TEXT NOT NULL,
    "ShiftNumber" INTEGER NOT NULL CHECK ("ShiftNumber" BETWEEN 1 AND 5),
    "IsPresent" INTEGER NOT NULL DEFAULT 0,
    "Note" TEXT,
    CONSTRAINT "FK_TeacherTimesheets_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers"("Id"),
    CONSTRAINT "UQ_TeacherTimesheets_TeacherId_WorkDate_ShiftNumber" UNIQUE ("TeacherId", "WorkDate", "ShiftNumber")
);

CREATE TABLE IF NOT EXISTS "TeacherMaterials" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TeacherId" BIGINT NOT NULL,
    "SubjectName" TEXT NOT NULL,
    "FileName" TEXT NOT NULL,
    "DriveFileId" TEXT NOT NULL,
    "DriveWebViewLink" TEXT,
    "UploadedAt" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "PaymentFinalizations" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClassId" BIGINT NOT NULL,
    "Month" INTEGER NOT NULL,
    "Year" INTEGER NOT NULL,
    "FinalizedAt" TEXT NOT NULL,
    "FinalizedBy" BIGINT NOT NULL,
    CONSTRAINT "FK_PaymentFinalizations_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "FK_PaymentFinalizations_Users_FinalizedBy" FOREIGN KEY ("FinalizedBy") REFERENCES "Users"("Id"),
    CONSTRAINT "UQ_PaymentFinalizations_ClassId_Month_Year" UNIQUE ("ClassId", "Month", "Year")
);

CREATE TABLE IF NOT EXISTS "StudentTuitionDiscounts" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StudentId" BIGINT NOT NULL,
    "Month" INTEGER NOT NULL,
    "Year" INTEGER NOT NULL,
    "DiscountPercent" NUMERIC(5,2) NOT NULL DEFAULT 0,
    "Note" TEXT,
    "CreatedBy" BIGINT NOT NULL,
    "CreatedAt" TEXT NOT NULL,
    CONSTRAINT "FK_StudentTuitionDiscounts_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "FK_StudentTuitionDiscounts_Users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "Users"("Id"),
    CONSTRAINT "UQ_StudentTuitionDiscounts_StudentId_Month_Year" UNIQUE ("StudentId", "Month", "Year")
);

CREATE TABLE IF NOT EXISTS "PaymentCarryOvers" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StudentId" BIGINT NOT NULL,
    "ClassId" BIGINT NOT NULL,
    "FromMonth" INTEGER NOT NULL,
    "FromYear" INTEGER NOT NULL,
    "ToMonth" INTEGER NOT NULL,
    "ToYear" INTEGER NOT NULL,
    "Amount" NUMERIC(18,2) NOT NULL,
    CONSTRAINT "FK_PaymentCarryOvers_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "FK_PaymentCarryOvers_Classes_ClassId" FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "UQ_PaymentCarryOvers_StudentId_ClassId_FromMonth_FromYear" UNIQUE ("StudentId", "ClassId", "FromMonth", "FromYear")
);

CREATE TABLE IF NOT EXISTS "Expenses" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ExpenseDate" TEXT NOT NULL,
    "Amount" NUMERIC(18,2) NOT NULL,
    "Category" TEXT NOT NULL,
    "Note" TEXT,
    "PaidBy" TEXT,
    "InvoiceNumber" TEXT,
    "AttachmentFileId" TEXT,
    "AttachmentFileName" TEXT,
    "AttachmentUrl" TEXT,
    "CreatedAt" TEXT NOT NULL,
    "CreatedBy" TEXT
);

-- Optional seed data (from current initializer behavior)
INSERT INTO "Teachers" ("FullName", "Phone", "Email", "Status")
SELECT 'Teacher Demo', '0900000002', 'teacher@demo.local', 'Active'
WHERE NOT EXISTS (
    SELECT 1 FROM "Teachers" WHERE "Email" = 'teacher@demo.local'
);

INSERT INTO "Users" ("Username", "PasswordHash", "Role", "TeacherId")
SELECT 'admin', '123456', 'Admin', NULL
WHERE NOT EXISTS (
    SELECT 1 FROM "Users" WHERE "Username" = 'admin'
);

INSERT INTO "Users" ("Username", "PasswordHash", "Role", "TeacherId")
SELECT 'teacher', '123456', 'Teacher', t."Id"
FROM "Teachers" t
WHERE t."Email" = 'teacher@demo.local'
  AND NOT EXISTS (
      SELECT 1 FROM "Users" WHERE "Username" = 'teacher'
  )
LIMIT 1;

COMMIT;
