-- Schema export for NhatDucSoftware (Supabase/PostgreSQL)
-- Generated from current SQLite model in application source.

BEGIN;

CREATE TABLE IF NOT EXISTS "Teachers" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName" TEXT NOT NULL,
    "Phone" TEXT,
    "Email" TEXT,
    "Status" TEXT NOT NULL DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username" TEXT NOT NULL UNIQUE,
    "PasswordHash" TEXT NOT NULL,
    "Role" TEXT NOT NULL,
    "TeacherId" BIGINT NULL,
    CONSTRAINT "FK_Users_Teachers_TeacherId"
        FOREIGN KEY ("TeacherId") REFERENCES "Teachers"("Id")
);

CREATE TABLE IF NOT EXISTS "Students" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName" TEXT NOT NULL,
    "Phone" TEXT,
    "Email" TEXT,
    "BirthYear" INTEGER NULL,
    "Address" TEXT NULL,
    "Language" TEXT NOT NULL,
    "Status" TEXT NOT NULL DEFAULT 'Active',
    "CreatedAt" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "Courses" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" TEXT NOT NULL UNIQUE,
    "Name" TEXT NOT NULL,
    "Language" TEXT NOT NULL,
    "TuitionFee" NUMERIC(18,2) NOT NULL,
    "DurationHours" INTEGER NOT NULL,
    "Status" TEXT NOT NULL DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS "Classes" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClassName" TEXT NOT NULL,
    "CourseId" BIGINT NOT NULL,
    "TeacherId" BIGINT NULL,
    "MaxSize" INTEGER NOT NULL,
    "Status" TEXT NOT NULL DEFAULT 'Active',
    CONSTRAINT "FK_Classes_Courses_CourseId"
        FOREIGN KEY ("CourseId") REFERENCES "Courses"("Id"),
    CONSTRAINT "FK_Classes_Teachers_TeacherId"
        FOREIGN KEY ("TeacherId") REFERENCES "Teachers"("Id")
);

CREATE TABLE IF NOT EXISTS "ClassSchedules" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClassId" BIGINT NOT NULL,
    "DayOfWeek" TEXT NOT NULL,
    "StartTime" TEXT NOT NULL,
    "EndTime" TEXT NOT NULL,
    "Room" TEXT,
    CONSTRAINT "FK_ClassSchedules_Classes_ClassId"
        FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id")
);

CREATE TABLE IF NOT EXISTS "ClassWeeklySchedules" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClassId" BIGINT NOT NULL,
    "WeekStartDate" TEXT NOT NULL,
    "DayOfWeek" INTEGER NOT NULL CHECK("DayOfWeek" BETWEEN 0 AND 6),
    "ShiftNumber" INTEGER NOT NULL CHECK("ShiftNumber" BETWEEN 1 AND 5),
    CONSTRAINT "FK_ClassWeeklySchedules_Classes_ClassId"
        FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "UQ_ClassWeeklySchedules_Class_Week_Day_Shift"
        UNIQUE ("ClassId", "WeekStartDate", "DayOfWeek", "ShiftNumber")
);

CREATE TABLE IF NOT EXISTS "StudentCourses" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StudentId" BIGINT NOT NULL,
    "CourseId" BIGINT NOT NULL,
    "EnrollDate" TEXT NOT NULL,
    "Status" TEXT NOT NULL,
    CONSTRAINT "FK_StudentCourses_Students_StudentId"
        FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "FK_StudentCourses_Courses_CourseId"
        FOREIGN KEY ("CourseId") REFERENCES "Courses"("Id")
);

CREATE TABLE IF NOT EXISTS "ClassStudents" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClassId" BIGINT NOT NULL,
    "StudentId" BIGINT NOT NULL,
    "JoinedDate" TEXT NOT NULL,
    CONSTRAINT "FK_ClassStudents_Classes_ClassId"
        FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "FK_ClassStudents_Students_StudentId"
        FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "UQ_ClassStudents_ClassId_StudentId"
        UNIQUE ("ClassId", "StudentId")
);

CREATE TABLE IF NOT EXISTS "Payments" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StudentId" BIGINT NOT NULL,
    "ClassId" BIGINT NULL,
    "Amount" NUMERIC(18,2) NOT NULL,
    "PaymentDate" TEXT NOT NULL,
    "Note" TEXT,
    "CreatedBy" BIGINT NOT NULL,
    CONSTRAINT "FK_Payments_Students_StudentId"
        FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "FK_Payments_Classes_ClassId"
        FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "FK_Payments_Users_CreatedBy"
        FOREIGN KEY ("CreatedBy") REFERENCES "Users"("Id")
);

CREATE TABLE IF NOT EXISTS "RevenueLedger" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourcePaymentId" BIGINT NULL UNIQUE,
    "Amount" NUMERIC(18,2) NOT NULL,
    "PaymentDate" TEXT NOT NULL,
    CONSTRAINT "FK_RevenueLedger_Payments_SourcePaymentId"
        FOREIGN KEY ("SourcePaymentId") REFERENCES "Payments"("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "AttendanceSessions" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClassId" BIGINT NOT NULL,
    "SessionDate" TEXT NOT NULL,
    "CreatedByTeacherId" BIGINT NOT NULL,
    CONSTRAINT "FK_AttendanceSessions_Classes_ClassId"
        FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "FK_AttendanceSessions_Teachers_CreatedByTeacherId"
        FOREIGN KEY ("CreatedByTeacherId") REFERENCES "Teachers"("Id")
);

CREATE TABLE IF NOT EXISTS "AttendanceRecords" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SessionId" BIGINT NOT NULL,
    "StudentId" BIGINT NOT NULL,
    "Status" TEXT NOT NULL,
    CONSTRAINT "FK_AttendanceRecords_AttendanceSessions_SessionId"
        FOREIGN KEY ("SessionId") REFERENCES "AttendanceSessions"("Id"),
    CONSTRAINT "FK_AttendanceRecords_Students_StudentId"
        FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "UQ_AttendanceRecords_SessionId_StudentId"
        UNIQUE ("SessionId", "StudentId")
);

CREATE TABLE IF NOT EXISTS "StudentEvaluations" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StudentId" BIGINT NOT NULL,
    "ClassId" BIGINT NOT NULL,
    "TeacherId" BIGINT NOT NULL,
    "Score" NUMERIC(5,2) NULL,
    "Comment" TEXT,
    "CreatedAt" TEXT NOT NULL,
    CONSTRAINT "FK_StudentEvaluations_Students_StudentId"
        FOREIGN KEY ("StudentId") REFERENCES "Students"("Id"),
    CONSTRAINT "FK_StudentEvaluations_Classes_ClassId"
        FOREIGN KEY ("ClassId") REFERENCES "Classes"("Id"),
    CONSTRAINT "FK_StudentEvaluations_Teachers_TeacherId"
        FOREIGN KEY ("TeacherId") REFERENCES "Teachers"("Id")
);

CREATE TABLE IF NOT EXISTS "TeacherTimesheets" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TeacherId" BIGINT NOT NULL,
    "WorkDate" TEXT NOT NULL,
    "ShiftNumber" INTEGER NOT NULL CHECK("ShiftNumber" BETWEEN 1 AND 5),
    "IsPresent" BOOLEAN NOT NULL DEFAULT FALSE,
    "Note" TEXT,
    CONSTRAINT "FK_TeacherTimesheets_Teachers_TeacherId"
        FOREIGN KEY ("TeacherId") REFERENCES "Teachers"("Id"),
    CONSTRAINT "UQ_TeacherTimesheets_TeacherId_WorkDate_ShiftNumber"
        UNIQUE ("TeacherId", "WorkDate", "ShiftNumber")
);

COMMIT;
