<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NhatDucSoftware.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.74.0.4135" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Npgsql" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NhatDucSoftware.Core.Tests" />
  </ItemGroup>

</Project>
